### ISSUE TITLE
Crash when :bp in a diff partnered window

### ISSUE THREAD

**Issue by idbrii** [idbrii/vim-diffusable#2]
Crash when :bp in a diff partnered window:

    (gdb) bt
    #0  0x0000000000544e04 in update_screen (type=<optimized out>) at screen.c:475
    #1  0x00000000005bcae7 in main_loop (cmdwin=0, noexmode=0) at main.c:1169
    #2  0x0000000000438804 in main (argc=<optimized out>, argv=<optimized out>) at main.c:967

That's on this line in screen.c at tag v7-3-426:

	if (wp->w_buffer->b_mod_set)

**Comment by idbrii** [comment]
It appears that updating to a later vim (622) fixes the crash. The vim commit acae400329989a7598e53452845a055c5daeba94 looks like it should fix it.
